# Server Port
server.port=8083

# Application Name
spring.application.name=spring-learn

# Enable DevTools automatic restart (optional)
spring.devtools.restart.enabled=true

# Logging Level (optional)
logging.level.org.springframework=INFO